### ISSUE TITLE
Incompatibility with tensorflow version in rnasamba (1,5-2) and keras (2.2<)

### ISSUE THREAD

**Issue by lucianofrancoo** [apcamargo/RNAsamba#11]
Hello, im trying to use RNAsamba but i have a few issues. Im ussing ubuntu 20.10 (groovy) where the default version of python is 3.8 and tensorflow is 2.3. So i proced to install RNAsamba  but it throws me the following error : 
![Screenshot from 2021-03-13 14-16-31](https://user-images.githubusercontent.com/80530322/111038255-c71a6c80-8406-11eb-9d81-6be07ac726c5.png)
So i tried to downgrade the version of my tensorflow but:
![Screenshot from 2021-03-13 14-17-14](https://user-images.githubusercontent.com/80530322/111038271-d7cae280-8406-11eb-9e83-a5c2f77410d2.png)
![Screenshot from 2021-03-13 14-17-36](https://user-images.githubusercontent.com/80530322/111038284-e1544a80-8406-11eb-9d65-6281b171bb81.png)
So i created a environment with python 3.5 and:
![Screenshot from 2021-03-13 14-21-41](https://user-images.githubusercontent.com/80530322/111038419-840cc900-8407-11eb-8e8c-f4a64f158462.png)
then i found out that biopython version 1.76 supports python 3.5 and installed it and finally was able to install RNAsamba. I tried to execute and: 
![Screenshot from 2021-03-13 14-26-48](https://user-images.githubusercontent.com/80530322/111038516-32187300-8408-11eb-9294-57ab05a3341d.png)
So i forced the upgrade of tensorflow to v 2.2 with pip install tensorflow==2.2 and in the end gives me this error and when i tried to execute RNAsamba it cant execute because it need tensorflow v 1.5-2:
![Screenshot from 2021-03-13 14-36-09](https://user-images.githubusercontent.com/80530322/111038787-87a14f80-8409-11eb-8c4f-238f6827d275.png)
After this is a chain of errors in a circle given the incompatibility between the version of tensorflow that keras occupies and RNAsamba .
Any help on this error is welcome :(

**Comment by apcamargo** [comment]
Hi @lucianofrancoo 

So, the problem is that RNAsamba does not support TensorFlow 2.0 yet, so forcing 2.2 won't solve. Are you using conda to create the environments? If so, create a Python 3.6 environment and install RNAsamba using this command:

```
conda install -c conda-forge -c bioconda rnasamba
```

Let me know if that solves your problem.

**Comment by lucianofrancoo** [comment]
Brrrpp thats work. With an environment in python 3.6. Thx for the help! have a nice day

**Comment by apcamargo** [comment]
You're welcome!
