### ISSUE TITLE
Using as a beginner

### ISSUE THREAD

**Issue by resulkiymaz1** [apcamargo/RNAsamba#13]
Hello there!

I have found this useful tool recently and I'm not good at with bioinformatics. So I made differential gene expression by Hisat2 and assemled all the transcript with stringtie. I want to calculate my transcrips' coding potential but I don't know how to change my gtf file to fasta file including the transcrips' sequences. Can you help me for this instance?

Best Regards..

**Comment by apcamargo** [comment]
Sure!

If you used StringTie you should have the genome FASTA file. You can use [gffread](http://ccb.jhu.edu/software/stringtie/gff.shtml#gffread) to extract the transcripts from it using a GTF:

```
gffread -w transcripts.fa -g /path/to/genome.fa transcripts.gtf
```

Let me know if this solves your issue.

**Comment by resulkiymaz1** [comment]
Thank you : Antônio Camargo  Windows 10 için Posta ile gönderildi Kimden: Antônio CamargoGönderilme: 19 Haziran 2021 Cumartesi 22:55Kime: apcamargo/RNAsambaBilgi: resulkiymaz1; AuthorKonu: Re: [apcamargo/RNAsamba] Using as a beginner (#13) Sure!If you used StringTie you should have the genome FASTA file. You can use gffread to extract the transcripts from it using a GTF:gffread -w transcripts.fa -g /path/to/genome.fa transcripts.gtf—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
