### ISSUE TITLE
Pip install not working

### ISSUE THREAD

**Issue by jaiganeshjg** [apcamargo/RNAsamba#14]
Not able to install RNAsamba with pip install due to conflicting dependencies. The error is provided below: 

`ERROR: Cannot install rnasamba==0.1.0, rnasamba==0.1.1, rnasamba==0.1.2, rnasamba==0.1.3, rnasamba==0.1.4, rnasamba==0.1.5, rnasamba==0.1.6, rnasamba==0.2.0, rnasamba==0.2.1, rnasamba==0.2.2, rnasamba==0.2.3, rnasamba==0.2.4 and rnasamba==0.2.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    rnasamba 0.2.5 depends on tensorflow<2.0 and >=1.5.0
    rnasamba 0.2.4 depends on tensorflow<2.0 and >=1.5.0
    rnasamba 0.2.3 depends on tensorflow<2.0 and >=1.5.0
    rnasamba 0.2.2 depends on tensorflow<2.0 and >=1.5.0
    rnasamba 0.2.1 depends on tensorflow<2.0 and >=1.5.0
    rnasamba 0.2.0 depends on tensorflow<2.0 and >=1.5.0
    rnasamba 0.1.6 depends on tensorflow<2.0 and >=1.5.0
    rnasamba 0.1.5 depends on tensorflow<2.0 and >=1.5.0
    rnasamba 0.1.4 depends on tensorflow<2.0 and >=1.5.0
    rnasamba 0.1.3 depends on tensorflow<2.0 and >=1.5.0
    rnasamba 0.1.2 depends on tensorflow<2.0 and >=1.5.0
    rnasamba 0.1.1 depends on tensorflow<2.0 and >=1.5.0
    rnasamba 0.1.0 depends on tensorflow<2.0 and >=1.5.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
`

**Comment by apcamargo** [comment]
Hi @jaiganeshjg. I'm not sure if I understand exactly what happened here. You tried to install multiple versions within the same environment?

Can you share the command you used to try to install RNAsamba?

**Comment by jaiganeshjg** [comment]
The command used was `pip install rnasamba`.

When the command `pip install rnasamba==0.2.5` is tried the error that we got was:

_ERROR: Could not find a version that satisfies the requirement tensorflow<2.0,>=1.5.0 (from rnasamba) (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.8.0rc0, 2.8.0rc1, 2.8.0)
ERROR: No matching distribution found for tensorflow<2.0,>=1.5.0_

**My system currently has python version - 3.9.7 and tensorflow version - 2.8.0**
Can you mention which python version and tensorflow version is required for running rnasamba?

**Comment by jaiganeshjg** [comment]
The installation worked with python v3.6. 

Thanks!

**Comment by apcamargo** [comment]
My guess is that the problem was TensorFlow 2.8.0. RNAsamba should work fine with Python 3.9, but it requires TensorFlow < 2.
