### ISSUE TITLE
Sequence number limit

### ISSUE THREAD

**Issue by mwylerCH** [apcamargo/RNAsamba#17]
Many thanks for developing RNAsamba.
Is it possible that the classification step has a limitation regarding the number of sequences in the input file?
If I split up the file into smaller chunks no issue arises.
However, no indications are given in the manual and no error message appears when the run is killed.
Many thanks in advance

**Comment by apcamargo** [comment]
Hi @mwylerCH.

There shouldn't be any limit to the number of sequences in the FASTA file. How many sequences are there in your input?

**Comment by mwylerCH** [comment]
Many thanks @apcamargo for the quick reply.
A file contains aroung 2 Mio sequences. It's maybe a issue with the memory?

**Comment by apcamargo** [comment]
That's probably it. You can split your input or cluster very similar sequences together.
