### ISSUE TITLE
Research objectives

### ISSUE THREAD

**Issue by Tang-pro** [apcamargo/RNAsamba#19]
Can this human training set be directly used on plants, such as cotton?

**Comment by apcamargo** [comment]
Yes. The model generalizes pretty well, so it should work fine in cotton data

**Comment by Tang-pro** [comment]
@apcamargo 
I want to know how rnasamba compares to GeneMarkS-T, because I used both methods and there were some differences in the results
Thank you!

**Comment by Tang-pro** [comment]
@apcamargo 
I want to know how rnasamba compares to GeneMarkS-T, because I used both methods and there were some differences in the results
Thank you！

**Comment by apcamargo** [comment]
There's no direct benchmark comparing the two tools, but based on how GeneMarkS-T works regarding classification into coding/non-coding I expect RNAsamba to perform much better. That said, GeneMarkS-T is still valuable to find the translated regions within coding transcript. You can use both tools.

**Comment by Tang-pro** [comment]
Thank you very much for your reply

**Comment by apcamargo** [comment]
No problem!
