### ISSUE TITLE
Coding score

### ISSUE THREAD

**Issue by Tang-pro** [apcamargo/RNAsamba#20]
Hi, @apcamargo 
I would like to ask if a coding score greater than 0.5 indicates coding, and a coding score less than 0.5 indicates non-coding. Why is this value used?
Best！

**Comment by apcamargo** [comment]
Just because it is the middle ground between 1.0 (very confident coding classification) and 0.0 (very confident non-coding classification).

**Comment by Tang-pro** [comment]
Thanks!
